services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "81:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "3001:300"
    volumes:
      - ./backend:/app
      - /app/node_modules
