version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "81:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
